
- hosts: all
  remote_user: D440745
  become: true

  tasks:
  - name: Install aptitude
    apt:
      name: aptitude
      state: latest
      update_cache: true

  - name: Install Python
    apt:
      name: python3
      state: latest
      update_cache: true

  - name: update
    apt:
     upgrade: dist
     force_apt_get: yes
  
  - name: install rsyslog
    apt:
     name: rsyslog
     state: latest
     update_cache: true

  - name: Install munin
    apt:
     name: munin
     state: latest
     update_cache: true
  
  - name: Install Apache2
    apt:
     name: 
     - apache2 
     - libcgi-fast-perl
     - libapache2-mod-fcgid
     state: latest
     update_cache: true

  - name: Edit rsyslog config
    lineinfile:
      dest: /etc/rsyslog.conf
      line: "{{ item }}"
    with_items:
    - '$ModLoad imudp'
    - '$UDPServerRun 514'
    - '$ModLoad imtcp'
    - '$InputTCPServerRun 50514'
    - '$AllowedSender TCP, 10.0.0.102/24, [::1]/128, *.example.net'
    - '$AllowedSender UDP, 10.0.0.102/24, [::1]/128, *.example.net'
    - '$AllowedSender TCP, 10.0.0.103/24, [::1]/128, *.example.net'
    - '$AllowedSender UDP, 10.0.0.103/24, [::1]/128, *.example.net'
    - '$template remote-incoming-logs, "/var/log/%HOSTNAME%/%PROGRAMNAME%.log"'
    - '*.* ?remote-incoming-logs'

  - name: Allow TCP
    ufw:
     rule: allow
     port: 50514
     proto: tcp
  
  - name: Allow UDP
    ufw:
     rule: allow
     port: 514
     proto: udp

  - name: ufw reload
    command: ufw reload

  - name: Edit munin conf file
    lineinfile:
      dest: /etc/munin/munin.conf
      line: "{{ item }}"
    with_items:
    - 'dbdir /var/lib/munin'
    - 'htmldir /var/cache/munin/www'
    - 'logdir /var/log/munin'
    - 'rundir /var/run/munin'

  - name: Configure Apache2
    ansible.builtin.file:
     src: "/etc/munin/apache24.conf"
     dest: "/etc/apache2/conf-enabled/munin.conf"
     state: link

  - name: Edit munin servers
    lineinfile:
     dest: /etc/munin/munin.conf
     line: "{{ item }}"
    with_items:
    - '[node0.example.com]'
    - '   address 10.0.0.102'
    - '   use_node_name yes'

  - name: Add munin plugin
    lineinfile:
     dest: /etc/munin/plugin-conf.d
     line: "{{ item }}"
    with_items:
    - '[docker_*]'
    - 'group docker'
    - 'env.DOCKER_HOST unix://run/docker.sock'
    - 'env.EXCLUDE_CONTAINER_NAME regexp'

  - name: restart apache2 & munin-node & rsyslog
    ansible.builtin.service:
      name: 
      - apache2
      - munin munin-node
      - rsyslog
      state: restarted
      enabled: true